### ISSUE TITLE
Add JS output tab in the UI to show the gaiman -> js transpiled code

### ISSUE THREAD

**Issue by rampall** [jcubic/gaiman#90]
This would help with debugging as well as showcasing how Gaiman works under the hood

**Comment by jcubic** [comment]
This is a feature that is already implemented. But it's hidden behind a dev mode checkbox. I use dev mode while working on the language.

I can make js output visible by default.

**Comment by jcubic** [comment]
The JS code is hidden by default to no scare people. Since this project is mainly created for people that are new to programming and want to create their Web Terminal. Using my library it maybe to difficult for some. You need to know HTML+CSS+JavaScript before you start creating the terminal. I wanted to simplify this so more people can use my library.

**Comment by rampall** [comment]
Ah, fair point. Somehow I missed that dev mode checkbox.
